image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3.0.0

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

distributionConfig:
  basicAuthUsers: []
  additionalEnvs: []

distributionNetwork:
  apiPort: 30095
  certificateID:
  hostNetwork: false

distributionRunAs:
  user: 568
  group: 568

distributionStorage:
  useFilesystemBackend: true
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []
