name: radarr
description: Radarr is a movie collection manager for Usenet and BitTorrent users.
annotations:
  title: Radarr
type: application
version: 1.2.28
apiVersion: v2
appVersion: 5.27.3.10153
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://github.com/Radarr/Radarr
icon: https://media.sys.truenas.net/apps/radarr/icons/icon.png
sources:
  - https://github.com/home-operations/containers/tree/main/apps/radarr
  - https://github.com/secretzer0/ix-charts/tree/master/community/radarr
  - https://github.com/Radarr/Radarr
keywords:
  - media
  - movies
