name: format_validation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      # Using our forked validation tools from GitHub Container Registry
      image: ghcr.io/secretzer0/ix_catalog_validation:latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: Validate catalog format
      run: |
        /bin/bash -c "PWD=${pwd}; /usr/local/bin/catalog_validate validate --path $PWD"
